### ISSUE TITLE
2. Adding a Template Engine to your Express App

### ISSUE THREAD

**Issue by nsafai** [MakeSchool-Tutorials/Node-Gif-Search#10]
On this step:

>  UPDATE YOUR HELLO WORLD ROUTE
> Let's update the hello world route to be a hello gif route.
> 
> // app.js
> 
> app.get('/hello-gif', function (req, res) {
>   var gifUrl = 'http://media2.giphy.com/media/gYBVM1igrlzH2/giphy.gif'
>   res.render('hello-gif', {gifUrl: gifUrl})
> })
> And define a new template in the views folder called hello-gif.handlebars that will display the gif image.
> 
> 
> <img src="{{gifUrl}}">

There's a permission issue on the gif image. Won't render (notice how it's not rendering above). When replaced with a different gif URL it just works.

**Comment by ibirnam** [comment]
@nsafai - tutorial has been revamped, this should be fixed now!
