### ISSUE TITLE
1. Setting up your NodeJS environment

### ISSUE THREAD

**Issue by jhaff** [MakeSchool-Tutorials/Node-Gif-Search#8]
in "Adding app.js" near the bottom

the word being is used in place of start or begin [the server]

Also, in the next section, the following chunk of text is repeated twice: 

 This is an example of an endpoint or route. It is called a GET route because we are "getting" information to read, not saving or changing information in the database. Hence, the function name we call is app.get(). Remember that app() is an instance of Express, and that means that the get() function is a native Express function (not middleware that we added).

-jacob

**Comment by jhaff** [comment]
Also, the next buttons change the page but do not scroll up :)

**Comment by ibirnam** [comment]
All of the above should be fixed now!
